/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 scene.gltf --transform
Author: ali-rahimi-shahmirzadi (https://sketchfab.com/ali-rahimi-shahmirzadi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soulless-1a18f6f206b14073884e1a9c31c03cbc
Title: Soulless
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Soulless(props) {
  const { nodes, materials, scene } = useGLTF('/soulless/scene-transformed.glb')

  console.log(nodes, materials)
  useEffect(() => {
    scene.traverse(child => child.material ? child.material.metalness = 0.5 : null)
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Head1Mesh_lambert3_0.geometry} material={materials.lambert3} />
    </group>
  )
}

useGLTF.preload('/soulless/scene-transformed.glb')
